### ISSUE TITLE
Something to improve upon

### ISSUE THREAD

**Issue by El-Potato-Slayer** [nikoescobal/Bubble-Sort#2]
Awesome job on this one man. There's one thing you can improve: 
https://github.com/nikoescobal/Bubble-Sort/blob/82df76118066d29102c00cd46afb637d14ccd412/bs-4.rb#L6-L10
You don't need a nested if-statement here. Try to reduce it to fewer lines.

**Comment by nikoescobal** [comment]
Thanks, bro. And cool, let me give that a try! 😄

**Comment by nikoescobal** [comment]
Made the changes bro. Let me know if this works 😃
