### ISSUE TITLE
Improvement for 4.5

### ISSUE THREAD

**Issue by El-Potato-Slayer** [nikoescobal/Bubble-Sort#3]
Once again, you've done an awesome job, but you can also reduce the nested if-statements.
https://github.com/nikoescobal/Bubble-Sort/blob/82df76118066d29102c00cd46afb637d14ccd412/bs-4.5.rb#L7-L13

**Comment by nikoescobal** [comment]
Will do, brother man!

**Comment by nikoescobal** [comment]
Added the changes bro.  😃
